-- MySQL Script generated by MySQL Workbench
-- Wed Oct 26 14:45:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quiz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quiz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quiz` DEFAULT CHARACTER SET utf8 ;
USE `quiz` ;

-- -----------------------------------------------------
-- Table `quiz`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`answers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  `is_right` TINYINT NOT NULL,
  `questions_id` INT NOT NULL,
  PRIMARY KEY (`id`, `is_right`, `questions_id`),
  CONSTRAINT `fk_answers_questions1`
    FOREIGN KEY (`questions_id`)
    REFERENCES `quiz`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `quiz`.`tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`tests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`tests_has_questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`tests_has_questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `questions_id` INT NOT NULL,
  `tests_id` INT NOT NULL,
  PRIMARY KEY (`id`, `questions_id`, `tests_id`),
  CONSTRAINT `fk_tests_has_questions_questions1`
    FOREIGN KEY (`questions_id`)
    REFERENCES `quiz`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tests_has_questions_tests1`
    FOREIGN KEY (`tests_id`)
    REFERENCES `quiz`.`tests` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`students_has_tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`students_has_tests` (
  `students_id` INT NOT NULL,
  `tests_id` INT NOT NULL,
  PRIMARY KEY (`students_id`, `tests_id`),
  CONSTRAINT `fk_students_has_tests_students1`
    FOREIGN KEY (`students_id`)
    REFERENCES `quiz`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_has_tests_tests1`
    FOREIGN KEY (`tests_id`)
    REFERENCES `quiz`.`tests` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `quiz`.`students_checks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`students_checks` (
  `id` VARCHAR(45) NOT NULL,
  `answers_id` INT NOT NULL,
  `students_id` INT NOT NULL,
  `tests_id` INT NOT NULL,
  `questions_id` INT NOT NULL,
  PRIMARY KEY (`id`, `answers_id`, `students_id`, `tests_id`, `questions_id`),
  CONSTRAINT `fk_students_answers_answers1`
    FOREIGN KEY (`answers_id`)
    REFERENCES `quiz`.`answers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_answers_students1`
    FOREIGN KEY (`students_id`)
    REFERENCES `quiz`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_answers_tests1`
    FOREIGN KEY (`tests_id`)
    REFERENCES `quiz`.`tests` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_answers_questions1`
    FOREIGN KEY (`questions_id`)
    REFERENCES `quiz`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
